CREATE TABLE Users ( 
	User_ID INT PRIMARY KEY AUTO_INCREMENT, 
	Email VARCHAR(255) UNIQUE, 
	Password VARCHAR(255) NOT NULL, 
	Username VARCHAR(255) UNIQUE 
);

CREATE TABLE Items ( 
	Item_ID INT PRIMARY KEY AUTO_INCREMENT, 
	Owner_ID INT NOT NULL, 
	Item_Name VARCHAR(255) NOT NULL, Item_Desc VARCHAR(255), 
	FOREIGN KEY (Owner_ID) REFERENCES Users(User_ID) 
);

CREATE TABLE Auctions ( 
	Auction_ID INT PRIMARY KEY AUTO_INCREMENT, 
	Item_ID INT NOT NULL, 
	Start_Price FLOAT NOT NULL, 
	Start_Time INT NOT NULL, 
	End_Time INT NOT NULL, 
	FOREIGN KEY (Item_ID) REFERENCES Items(Item_ID)
);

CREATE TABLE Bids ( 
	Bid_ID INT PRIMARY KEY AUTO_INCREMENT, 
	Bidder_Id INT NOT NULL, 
	Auction_ID INT NOT NULL, 
	Price FLOAT NOT NULL, 
	Time_Placed INT NOT NULL, 
	FOREIGN KEY (Bidder_ID) REFERENCES Users(User_ID), 
	FOREIGN KEY (Auction_ID) REFERENCES Auctions(Auction_ID)
);

CREATE TABLE Transactions (
	Transaction_ID INT PRIMARY KEY AUTO_INCREMENT,
	Buyer_ID INT NOT NULL,
	Auction_ID INT NOT NULL,
	FOREIGN KEY (Buyer_ID) REFERENCES Users(User_ID),
	FOREIGN KEY (Auction_ID) REFERENCES Auctions(Auction_ID)
);

